name: 'lint-yaml'
description: 'Lints YAML files'

inputs:
  yamlfmt-version:
    description: 'yamlfmt version'
    default: 'v0.17.0'
    required: false

runs:
  using: "composite"
  steps:
    - name: Install yamlfmt
      uses: jaxxstorm/action-install-gh-release@6096f2a2bbfee498ced520b6922ac2c06e990ed2 # v2.1.0
      with:
        repo: google/yamlfmt
        tag: ${{ inputs.yamlfmt-version }}
    - name: Run yamlfmt
      shell: bash
      run: |
        yamlfmt \
          -lint \
          -quiet \
          -formatter 'retain_line_breaks_single=true' \
          $(git ls-files '*.yml' '*.yaml')
