name: 'goreleaser'
description: 'Release Go binaries using GoReleaser'

inputs:
  gh-token:
    description: 'GitHub token to use with goreleaser'
    required: true

runs:
  using: "composite"
  steps:
    - name: Set up Go
      uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6.2.0
      with:
        go-version-file: 'go.mod'
    - name: Install Cosign
      uses: sigstore/cosign-installer@faadad0cce49287aee09b3a48701e75088a2c6ad # v4.0.0
      with:
        cosign-release: 'v3.0.4'
    - name: Release Binaries
      uses: goreleaser/goreleaser-action@e435ccd777264be153ace6237001ef4d979d3a7a # v6.4.0
      with:
        version: 'v2.13.3'
        args: release --clean
      env:
        GITHUB_TOKEN: ${{ inputs.gh-token }}
