name: 'lint-sh'
description: 'Lints shell scripts'

inputs:
  shellcheck-version:
    description: 'shellcheck version'
    default: 'v0.10.0'
    required: false
  pattern:
    description: 'file pattern'
    default: '*.sh'
    required: false

runs:
  using: "composite"
  steps:
    - name: Install shellcheck
      uses: jaxxstorm/action-install-gh-release@6096f2a2bbfee498ced520b6922ac2c06e990ed2 # v2.1.0
      with:
        repo: koalaman/shellcheck
        tag: ${{ inputs.shellcheck-version }}
    - name: Run shellcheck
      shell: bash
      run: |
        shellcheck \
          $(git ls-files ${{ inputs.pattern }})
