name: 'scan-files'
description: 'Scans files using virus total'

inputs:
  files:
    description: 'files to scan'
    required: true
  vt-api-key:
    description: 'virus-total api key'
    required: true
  vt-version:
    description: 'virus-total version'
    default: '1.1.1'
    required: false

runs:
  using: "composite"
  steps:
    - name: Install vt-cli
      shell: bash
      run: |
        ${{ github.action_path }}/install-vt.sh "${{ inputs.vt-version }}"
    - name: Run scan
      shell: bash
      env:
        VTCLI_APIKEY: ${{ inputs.vt-api-key }}
      run: |
        bash -c '${{ github.action_path }}/scan.sh ${{ inputs.files }}'
