name: 'scan-files'
description: 'Scans files using virus total'

inputs:
  files:
    description: 'files to scan'
    required: true
  vt-api-key:
    description: 'virus-total api key'
    required: true
  vt-version:
    description: 'virus-total version'
    default: 'v1.1.1'
    required: false

runs:
  using: "composite"
  steps:
    - name: Install vt-cli
      uses: jaxxstorm/action-install-gh-release@6096f2a2bbfee498ced520b6922ac2c06e990ed2 # v2.1.0
      with:
        repo: VirusTotal/vt-cli
        tag: ${{ inputs.vt-version }}
    - name: Run scan
      shell: bash
      env:
        VTCLI_APIKEY: ${{ inputs.vt-api-key }}
      run: |
        ./scan.sh "${{ inputs.files }}"
