name: 'cargo-deny'
description: 'Run cargo deny'

runs:
  using: "composite"
  steps:
    - name: Install toolchain
      uses: actions-rust-lang/setup-rust-toolchain@v1
    - name: Install cargo-deny
      uses: jaxxstorm/action-install-gh-release@6096f2a2bbfee498ced520b6922ac2c06e990ed2 # v2.1.0
      with:
        repo: EmbarkStudios/cargo-deny
    - name: cargo deny
      shell: bash
      run: cargo deny check
