name: 'govulncheck'
description: 'Run govulncheck'

runs:
  using: "composite"
  steps:
    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version-file: 'go.mod'
    - name: install govulncheck
      shell: bash
      run: go install golang.org/x/vuln/cmd/govulncheck@latest
    - name: govulncheck
      shell: bash
      run: govulncheck ./...
